### ISSUE TITLE
Integration with Concorda - Use Concorda's login page

### ISSUE THREAD

**Issue by mirceaalexandru** [vidi-insights/vidi-dashboard#100]
This will allow Vidi to use Google auth service implemented in Concorda

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Do you want to open a new branch with your updated script for Concorda?

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Just a heads up We are going to get the sign on buttons done via #118 You will be able to copy them from Concorda then.

**Comment by mcdonnelldean** [comment]
@mirceaalexandru Integration is done now right? Just via redirect

**Comment by mirceaalexandru** [comment]
@mcdonnelldean for Google login, not for local strategy, but it was already in the next demo schedule. Do you need that feature?

**Comment by mcdonnelldean** [comment]
Nope, Looking to close this.
