### ISSUE TITLE
Can we style charts (Spike)

### ISSUE THREAD

**Issue by mcdonnelldean** [vidi-insights/vidi-dashboard#117]
In terms of charts I'd like to see if we can,

- Style all the lines charts so that they use 'on brand' colors
- Make the lines on the line charts slightly thinner

Generally I'm more interested in seeing what sort of ability we have to style the charts so don't sweat it too much if it turns out it's more involved than first thought.

**Comment by thefoxis** [comment]
Because Chartist has the source in Sass I had to port it in CSS (hence no variables). The stroke line is thinner and the colours are on brand + some complementary colours and shades. Removed external reference to CDN too.
