### ISSUE TITLE
Add Social signon button

### ISSUE THREAD

**Issue by mcdonnelldean** [vidi-insights/vidi-dashboard#118]
@mirceaalexandru Is working on bringing in various integrations for Vidi through concorda. Right now he has Google working. Can we add some UI to have a number of social signon buttons? As far as I am aware we aren't going to go much further GH / Google Twitter. So a button for each would be perfect.

They don't need to do anything with them, just add the UI

**Comment by thefoxis** [comment]
closed via 7e989e9e95f46eaf1ad5f43c568e77fece256450
