### ISSUE TITLE
not closing up connections properly

### ISSUE THREAD

**Issue by mcollina** [vidi-insights/vidi-dashboard#130]
Error: bind EMFILE 0.0.0.0
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at dgram.js:213:18
    at doNTCallback3 (node.js:452:9)
    at process._tickDomainCallback (node.js:399:17)

Under load `wrk -c 1000 -d 10 http://localhost:3000/`

**Comment by mcdonnelldean** [comment]
I'll need to do a review of Vidi: Metrics with you @mcollina to resolve this stuff.

**Comment by mcollina** [comment]
Sure thing, can you point me to the relevant module? I'll have a look

**Comment by mcdonnelldean** [comment]
@mcollina Yup,

This is the one, https://github.com/vidi-insights/vidi-metrics/blob/master/vidi-metrics.js

**Comment by mcdonnelldean** [comment]
@mcollina I think this came from Toolbag, updated to 0.8.0. The JSON circular is also from Toolbag :(
