### ISSUE TITLE
Style /profile

### ISSUE THREAD

**Issue by mcdonnelldean** [vidi-insights/vidi-dashboard#59]
Due next iteration

**Comment by thefoxis** [comment]
Want to give more insight into what should go into that page?

**Comment by mcdonnelldean** [comment]
I will as soon as I know :D We are due to bring this up at the next demo. I think it will end up being basic name / email combo with some buttons for password reset, etc. But not 100% yet.

**Comment by mcdonnelldean** [comment]
Assigned to me until I figure out what should be here.

**Comment by mcdonnelldean** [comment]
@thefoxis I'd say add the following here for now,

- User
- Email

-edit button
- reset password button

For now that is all we needed (we'll add more in later iterations)
